# Stubs for undefined functions/variables in MULTI_SYMBOLS_NOSIGNALCLOSE.py
from typing import Any

def sync_windows_silently() -> None: ...
def check_network_connectivity() -> bool: ...
def _generate_client_order_id(order_type: str) -> str: ...
def safe_market_sell(symbol: str, quantity: float) -> None: ...
def compute_position_size_by_risk(equity: float, atr_value: float, entry_price: float) -> float: ...
def compute_position_size_fixed_notional(equity: float, notional_per_trade_usd: float, entry_price: float) -> float: ...
def compute_position_size_volatility_parity(equity: float, atr_value: float, entry_price: float, target_volatility_pct: float) -> float: ...
real_trading_pair: str = ''
def init_timestamp_solution() -> bool: ...
def cleanup_expired_cache() -> None: ...
all_results: dict = {}
def execute_real_trades(real_pair: str, timeframe: Any, best_params: Any, backtest_pair: str) -> None: ...
def execute_scheduled_trading(real_pair: str, timeframe: Any, params: dict, backtest_pair: str) -> None: ...
